on:
  push:
    branches: ['master']
  pull_request:
    branches: '**'
  schedule:
    - cron: '0 7 * * 3'
    - cron: '0 6 * * 1'

permissions:
  contents: read
  
jobs:
  semgrep:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Semgrep Scan
    runs-on: ubuntu-latest
    
    container:
      image: returntocorp/semgrep
      
    steps:
      - uses: actions/checkout@v3
    
      - name: Install Semgrep dependencies
        run: python3 -m pip install ansi2html
        
      - name: Run semgrep
        run: semgrep scan --sarif --output=semgrep.sarif --config=policy
        env:
          SEMGREP_RULES: >-
            p/ci 
            p/r2c-best-practices
            p/r2c-bug-scan 
            p/r2c-ci  
            p/secrets 
            p/security-audit 
            
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
      
